// get_arr_words_for_development


export const WORDS_FOR_DEVELOPMENT = [

    {enW: "accountant",     ruW: "бухгалтер",                           isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "acquaintance",   ruW: "знакомый, знакомство",                isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "actor",          ruW: "художник",                            isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "airport",        ruW: "масаэропортло",                       isAudio: {exists: true},  isRepeat: {exists: true,  dictionary: false, project: 'пробный проект'},},
    {enW: "also",           ruW: "точно так же",                        isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "animal",         ruW: "animal",                              isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "apple",          ruW: "яблоко",                              isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "apricot",        ruW: "абрикос",                             isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "armchair",       ruW: "кресло",                              isAudio: {exists: true},  isRepeat: {exists: true,  dictionary: false, project: 'пробный проект'},},
    {enW: "artist",         ruW: "художник",                            isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "aunt",           ruW: "тетя",                                isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "balcony",        ruW: "балкон",                              isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "banana",         ruW: "банан",                               isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "bank",           ruW: "банк",                                isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "bathroom",       ruW: "ванная",                              isAudio: {exists: true},  isRepeat: {exists: true,  dictionary: false, project: 'пробный проект'},},
    {enW: "beach",          ruW: "пляж",                                isAudio: {exists: false}, isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "beans",          ruW: "бобы",                                isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "bear",           ruW: "медведь",                             isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "bed",            ruW: "кровать",                             isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "bedroom",        ruW: "спальня",                             isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "beef",           ruW: "говядина",                            isAudio: {exists: true},  isRepeat: {exists: true,  dictionary: false, project: 'Мой первый проект'},},
    {enW: "beet",           ruW: "свекла",                              isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "berry",          ruW: "ягода",                               isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "bird",           ruW: "птица",                               isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "border",         ruW: "граница",                             isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "boss",           ruW: "босс",                                isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "boy",            ruW: "мальчик",                             isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "bread",          ruW: "хлеб",                                isAudio: {exists: false}, isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "bridge",         ruW: "мост",                                isAudio: {exists: false}, isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "brother",        ruW: "брат",                                isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "building",       ruW: "здание, строительство",               isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "businessman",    ruW: "бизнесмен",                           isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},   
    {enW: "butter",         ruW: "масло",                               isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "cabbage",        ruW: "капуста",                             isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "cabinet",        ruW: "шкаф чик",                            isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "cafe",           ruW: "кафе",                                isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "carpet",         ruW: "ковер",                               isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "carrot",         ruW: "морковь",                             isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "cat",            ruW: "кошка",                               isAudio: {exists: false}, isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "ceiling",        ruW: "потолок",                             isAudio: {exists: false}, isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "center",         ruW: "центр",                               isAudio: {exists: false}, isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "chair",          ruW: "стул",                                isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "cheese",         ruW: "сыр",                                 isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "cherry",         ruW: "вишня",                               isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "chicken",        ruW: "цыпленок, курица",                    isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "chief",          ruW: "начальник, шеф, главный, вождь",      isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "child",          ruW: "ребенок",                             isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "chimney",        ruW: "дымовая труба",                       isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "church",         ruW: "церковь",                             isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "cinema",         ruW: "кинотеатр",                           isAudio: {exists: false}, isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "city",           ruW: "город",                               isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "client",         ruW: "клиент",                              isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "coast",          ruW: "морской берег, побережье",            isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "colleague",      ruW: "коллега",                             isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "company",        ruW: "компания, фирма",                     isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "competitor",     ruW: "конкурент, соперник",                 isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "corn",           ruW: "кукуруза, зерно",                     isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "country",        ruW: "страна, сельская местность",          isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "cousin",         ruW: "двоюродный брат, двоюродная сестра",  isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "cow",            ruW: "корова",                              isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "crossroads",     ruW: "перекрёсток",                         isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "cucumber",       ruW: "огурец",                              isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "curtain",        ruW: "занавес ка, штора",                   isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "customs",        ruW: "таможня",                             isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "cutlet",         ruW: "котлета",                             isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "dad",            ruW: "папа",                                isAudio: {exists: false}, isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "daughter",       ruW: "дочь",                                isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "doctor",         ruW: "врач",                                isAudio: {exists: true},  isRepeat: {exists: true,  dictionary: false, project: 'Мой первый проект'},},
    {enW: "dog",            ruW: "собака",                              isAudio: {exists: false}, isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "door",           ruW: "дверь",                               isAudio: {exists: true},  isRepeat: {exists: true,  dictionary: false, project: 'Мой первый проект'},},
    {enW: "driver",         ruW: "водитель",                            isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "duck",           ruW: "утка",                                isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "egg",            ruW: "яйцо",                                isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "eggplant",       ruW: "баклажан",                            isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "elephant",       ruW: "слон",                                isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "engineer",       ruW: "инженер",                             isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "England",        ruW: "Англия",                              isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "entrance",       ruW: "вход",                                isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "exit",           ruW: "выход",                               isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "factory",        ruW: "предприятие, завод, фабрика",         isAudio: {exists: false}, isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "family",         ruW: "семья",                               isAudio: {exists: false}, isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "father",         ruW: "отец",                                isAudio: {exists: false}, isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "faucet",         ruW: "водопроводный кран",                  isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "fence",          ruW: "забор",                               isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "field",          ruW: "поле",                                isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "fish",           ruW: "рыба, рыбачить",                      isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "five",           ruW: "пять",                                isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "flat",           ruW: "квартира",                            isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "floor",          ruW: "пол, этаж",                           isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "flour",          ruW: "мука",                                isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "flower",         ruW: "цветок",                              isAudio: {exists: false}, isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "food",           ruW: "еда",                                 isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "forest",         ruW: "лес",                                 isAudio: {exists: false}, isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "fox",            ruW: "лиса",                                isAudio: {exists: false}, isRepeat: {exists: true,  dictionary: false, project: 'Мой первый проект'},},
    {enW: "fridge",         ruW: "холодильник",                         isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "friend",         ruW: "друг",                                isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "frog",           ruW: "лягушка",                             isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "fruit",          ruW: "фрукты, плод",                        isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "furniture",      ruW: "мебель",                              isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "garbage",        ruW: "мусор",                               isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "garden",         ruW: "сад",                                 isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "garlic",         ruW: "чеснок",                              isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "giraffe",        ruW: "жираф",                               isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "girl",           ruW: "девочка",                             isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "goose",          ruW: "гусь",                                isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "grandfather",    ruW: "дед",                                 isAudio: {exists: false}, isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "grape",          ruW: "виноград",                            isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "grass",          ruW: "трава",                               isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "Great Britain",  ruW: "Великобритания",                      isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "guest",          ruW: "гость",                               isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "guy",            ruW: "парень",                              isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "hall",           ruW: "коридор",                             isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "ham",            ruW: "ветчина",                             isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "hello",          ruW: "здравствуйте",                        isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "hi",             ruW: "привет",                              isAudio: {exists: false}, isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "home",           ruW: "дом место проживания",                isAudio: {exists: false}, isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "horse",          ruW: "лошадь",                              isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "hospital",       ruW: "больница",                            isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "hotel",          ruW: "гостиница",                           isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "house",          ruW: "дом",                                 isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "how",            ruW: "как",                                 isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "husband",        ruW: "муж",                                 isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "island",         ruW: "остров",                              isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "job",            ruW: "работа",                              isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "journalist",     ruW: "журналист",                           isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "just",           ruW: "только что",                          isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "kitchen",        ruW: "кухня",                               isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "lake",           ruW: "озеро",                               isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "lamb",           ruW: "баранина, ягненок",                   isAudio: {exists: false}, isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "land",           ruW: "земля, участок",                      isAudio: {exists: false}, isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "lawyer",         ruW: "адвокат, юрист",                      isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "leaf",           ruW: "лист дерева",                         isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "living room",    ruW: "зал",                                 isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "man",            ruW: "мужчина",                             isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "market",         ruW: "рынок",                               isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "meat",           ruW: "мясо",                                isAudio: {exists: false}, isRepeat: {exists: true,  dictionary: false, project: 'Проект 5'},},
    {enW: "melon",          ruW: "дыня",                                isAudio: {exists: false}, isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "microwave",      ruW: "микроволновка",                       isAudio: {exists: false}, isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "mirror",         ruW: "зеркало",                             isAudio: {exists: false}, isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "monkey",         ruW: "обезьяна",                            isAudio: {exists: false}, isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "mother",         ruW: "мать",                                isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "mountain",       ruW: "гора",                                isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "mouse",          ruW: "мышь",                                isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "mum",            ruW: "мама",                                isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "mushroom",       ruW: "гриб",                                isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "musician",       ruW: "музыкант",                            isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "neighbor",       ruW: "сосед",                               isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "nephew",         ruW: "племянник",                           isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "niece",          ruW: "племянница",                          isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "no",             ruW: "нет",                                 isAudio: {exists: false}, isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "noodles",        ruW: "лапша",                               isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "now",            ruW: "сейчас",                              isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "nurse",          ruW: "медсестра",                           isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "nut",            ruW: "орех",                                isAudio: {exists: false}, isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "oatmeal",        ruW: "овсянка",                             isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "ocean",          ruW: "океан",                               isAudio: {exists: true},  isRepeat: {exists: true,  dictionary: false, project: 'Проект 5'},},
    {enW: "office",         ruW: "офис",                                isAudio: {exists: false}, isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "oil",            ruW: "растительное масло, нефть",           isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "onion",          ruW: "лук репчатый",                        isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "oven",           ruW: "печь, духовка",                       isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "parents",        ruW: "родители",                            isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "park",           ruW: "парк",                                isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "path",           ruW: "тропа, тропинка",                     isAudio: {exists: false}, isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "pea",            ruW: "горох",                               isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "peach",          ruW: "персик",                              isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},
    {enW: "pear",           ruW: "груша",                               isAudio: {exists: true},  isRepeat: {exists: false, dictionary: false, project: false},},


];